language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: BCTzp9L5Qir7N+a9W01/DS/4KgzpApRp/vz9yUVZ8Z3V2whiJQHSzllXaRCGdc84niFePIo0KYMUXxYD59w2ZR5tNPZXNTCC8AAOMYMB/TcpMpN1uYjH1ZvPh4WIpEtRlSisgvVqhc31/q0P6tMUGnQDnpA7wU/vSkFc5phd9usOY9tAATkHGSsrql9Qiras6sxmz7gQ9RRxWtWvOLv+Eupk4ItnHCrW0ygJiJjw0SckXDM4uH1dZBV53iviEszifNZEwVAmHSZOZI/+M1iepdQQCgi15m5GmcFvaeCy9Tw/Xp+CwsJfvor5S6TcUv4PC7N5p/a+j7Eq2O5JPeQe1bOU2piYGjRwPFAbbu41jeE+QQXN7wagq8sMeXTJ4tCz0oxihqNKcNlSjcP6402S9UizU4zBNHJDnvWXAuz/Wze9I0cUNi540xaKSEOxyJJtJ6OZVZoPq7FDe3bX+VZEcfKNPw9nZ1X6iYil5dv339kl4Z/gSS32Av8rjwhrCiJp9xoUzp3YhfEVd6Urao5m4k6qitwSnLvRYphJkmQ+SBV3clzWnLfIUvsnmA7rSQBCZsLKGBo+VM3FzGZ/AjzziiXsR3jEiaQkznAl5ibWKoHsx0f7UvuE0hXo2x1PN+7D6SSsYgbztRNEg3hSTT7qkYwRxo2NwqU70WBw1DrFSEo=
  app: blackjack-mandatory
