language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: TxWzktXNEXN4BSgBP2j1iNwNkJM/98TaRqsD0Tl6sIONIE4sQcopo7zVCyo0tQfLfjgL7zM9G7umJ/lSygMKezF6XWmwD1YpuJFNoqeudkUYYS/IzdOtIz0090PFnOxgx12fz3smFghaLp51ef5+DUgoPsRmrtiGrkRTQUy9Yny77D16b36z8ShRsZhieW80FreFfLkg98M+r2KTJLS3A7MWTAB8db8TtQ645bbSrgV+3/qIsIqxmVaPxVlsgYThGqbE5FxtIoPMtfP32xlOj9ZH66gtFdobIpBJc3Nv5ebQMOYPMAI/AWKxKQLIxHsJOBkrw5VGEGGVAOmAjp2DQGXdjFgk6LMjp0Mw+9H7S/vKvcn/YgV9lIvs4F03N0dQDZLBwcf2XgbcSJuPBi0Ip7Nm6ewdRCkXKZaZNHWtalxsk7kLOtG4t2vqcDP0HEUIi417pLVU1PS1OtgD7FK/drsBJdftANt3tHgtmomsI1Rv+B8b1sFqZYgCH7qZZj5PFgxdH2fmHX1c594YLvkxwIcg7kceUopUg6UtyafWggXjrDWi4P2v0GnLvinNdNOa7AQIdh7Wvs1dxdtPuzBReKR48rnBuq5kglOaxZ18Lizykuor/bjXOltmNgPWlSIHorV/kE4XMeB0BvAefDFO/PYWk0w8qPwaHVcqGXSomqU=
  app: app-simple-notes
before_install:
- chmod +x mvnw
