language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: "AAAAB3NzaC1yc2EAAAADAQABAAACAQCaQoAd3hCD1vZcDYewsjUWf6SFGhAB7y1kxRkGtHYdTfvEM/mPPT/RQzLqzvnVo4Inx4Dt79TImitDo74TRG2URNRrR4nmievxNcbHlyQeswzlxWqkrqZca/Baj3KBDG1ixnJILIsQZ/f0MbQELXhnIcBRRmdt3uyLKxgQusiY1njepSoxliq81wyPvLAFs7p3oSaiobGwrjMda3KxorjEkTqpZyaE53I2D2t+ZnSQaUMaZ068tnEeVig+VtWkG9zO0tXeMSrs39uqWhAmmNTDzPGKVdNZPIEqW/IJXT3jdNDlV9TDcv1k2ClCRuleOYKKWvAM9rGMnlY+X4WiKiJPXrgTKsTrVxGHmcUHcaR2Hw99PuzsyiboajVsB0o6AvMMyRomrz1cMFC72Ck3XFGOqUq110tBkxqMgLdp4B7b4h86b8gEcEXmRyylDv+gIvMw1czv4O6xUkv5K23B56NzwrqnGlmZWh0M1chsRDcqs3wt+xy8oe2rEkGidlKIj1eTDmSbUIOtKDTOqoUR7hLD5IWLGMN2xgC9cASjLDHjB6EOz3IzNfR1mCZg50ZC6JdcL83851/ij5iEbsw0ktrHfH49lJBWyIGSm4LAdCqbqmTyuVbxNhMMBnXXf42cQMHMd3lgVReGyHmNn2dLo59oZr5L35PvNKKPHgFp58qUBw=="
      app: app-simple-notes
before_install:
  - chmod +x mvnw